name: test
on:
  pull_request:
    branches:
    - master

jobs:
  lint:
    name: Lint checking on Ubuntu
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go 1.25.3
      uses: actions/setup-go@v6
      with:
        go-version: '1.25.3'
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v5

    - name: Running golangci-lint
      uses: golangci/golangci-lint-action@v8
      with:
        version: latest

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go 1.25.3
      uses: actions/setup-go@v6
      with:
        go-version: '1.25.3'
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v5

    - name: Running go tests
      run: make test

